const ExpensesActionsTypes = {
    FETCH_EXPENSES_REQUEST: 'FETCH_EXPENSES_REQUEST',
    FETCH_EXPENSES_SUCCESS: 'FETCH_EXPENSES_SUCCESS',
    FETCH_EXPENSES_FAILURE: 'FETCH_EXPENSES_FAILURE',
    ADD_EXPENSE_ITEM_REQUEST: 'ADD_EXPENSE_ITEM_REQUEST',
    ADD_EXPENSE_ITEM_SUCCESS: 'ADD_EXPENSE_ITEM_SUCCESS',
    ADD_EXPENSE_ITEM_FAILURE: 'ADD_EXPENSE_ITEM_FAILURE',
    REMOVE_EXPENSE_ITEM_REQUEST: 'REMOVE_EXPENSE_ITEM_REQUEST',
    REMOVE_EXPENSE_ITEM_SUCCESS: 'REMOVE_EXPENSE_ITEM_SUCCESS',
    REMOVE_EXPENSE_ITEM_FAILURE: 'REMOVE_EXPENSE_ITEM_FAILURE',
};

export default ExpensesActionsTypes;
