const TripsActionsTypes = {
    FETCH_TRIPS_REQUEST: 'FETCH_TRIPS_REQUEST',
    FETCH_TRIPS_SUCCESS: 'FETCH_TRIPS_SUCCESS',
    FETCH_TRIPS_FAILURE: 'FETCH_TRIPS_FAILURE',
    ADD_TRIP_REQUEST: 'ADD_TRIP_REQUEST',
    ADD_TRIP_SUCCESS: 'ADD_TRIP_SUCCESS',
    ADD_TRIP_FAILURE: 'ADD_TRIP_FAILURE',
    REMOVE_TRIP_REQUEST: 'REMOVE_TRIP_REQUEST',
    REMOVE_TRIP_SUCCESS: 'REMOVE_TRIP_SUCCESS',
    REMOVE_TRIP_FAILURE: 'REMOVE_TRIP_FAILURE',
    SET_ACTIVE_TRIP_START: 'SET_ACTIVE_TRIP_START',
    SET_ACTIVE_TRIP: 'SET_ACTIVE_TRIP',
};

export default TripsActionsTypes;
