const TripsActionsTypes = {
    FETCH_TRIPS_REQUEST: 'FETCH_TRIPS_REQUEST',
    FETCH_TRIPS_SUCCESS: 'FETCH_TRIPS_SUCCESS',
    FETCH_TRIPS_FAILURE: 'FETCH_TRIPS_FAILURE',
    ADD_TRIP_REQUEST: 'ADD_TRIP_REQUEST',
    ADD_TRIP_SUCCESS: 'ADD_TRIP_SUCCESS',
    ADD_TRIP_FAILURE: 'ADD_TRIP_FAILURE',
    REMOVE_TRIP: 'REMOVE_TRIP',
};

export default TripsActionsTypes;
