export const expenses = [
    {
        date: '2020.04.28',
        hour: '10:28',
        name: 'Item 1',
        tags: ['food', 'tickets', 'living'],
        value: 10,
        currency: 'USD',
    },
    {
        date: '2020.04.28',
        hour: '10:28',
        name: 'Item 2',
        tags: ['food', 'tickets', 'living'],
        value: 10,
        currency: 'CAD',
    },
    {
        date: '2020.04.28',
        hour: '10:28',
        name: 'Item 3',
        tags: ['food', 'tickets', 'living'],
        value: 10,
        currency: 'PLN',
    },
    {
        date: '2020.04.28',
        hour: '10:28',
        name: 'Item 4',
        tags: ['food', 'tickets', 'living'],
        value: 10,
        currency: 'AED',
    },
    {
        date: '2020.04.28',
        hour: '10:28',
        name: 'Item 5',
        tags: ['food', 'tickets', 'living'],
        value: 10,
        currency: 'AMD',
    },
    {
        date: '2020.04.28',
        hour: '10:28',
        name:
            'To jest jakiś bardzo długi tekst opisujący na co poszło tyle hajsu',
        tags: ['food', 'tickets', 'living'],
        value: 10,
        currency: 'AZN',
    },
    {
        date: '2020.04.28',
        hour: '10:28',
        name: 'Item 7',
        tags: ['food', 'tickets', 'living'],
        value: 10,
        currency: 'CLP',
    },
    {
        date: '2020.04.28',
        hour: '10:28',
        name: 'Item 8',
        tags: ['food', 'tickets', 'living'],
        value: 10,
        currency: 'EGP',
    },
];
