const ItineraryActionsTypes = {
    FETCH_ITINERARY_REQUEST: 'FETCH_ITINERARY_REQUEST',
    FETCH_ITINERARY_SUCCESS: 'FETCH_ITINERARY_SUCCESS',
    FETCH_ITINERARY_FAILURE: 'FETCH_ITINERARY_FAILURE',
    ADD_ITINERARY_ITEM_REQUEST: 'ADD_ITINERARY_ITEM_REQUEST',
    ADD_ITINERARY_ITEM_SUCCESS: 'ADD_ITINERARY_ITEM_SUCCESS',
    ADD_ITINERARY_ITEM_FAILURE: 'ADD_ITINERARY_ITEM_FAILURE',
    REMOVE_ITINERARY_ITEM_REQUEST: 'REMOVE_ITINERARY_ITEM_REQUEST',
    REMOVE_ITINERARY_ITEM_SUCCESS: 'REMOVE_ITINERARY_ITEM_SUCCESS',
    REMOVE_ITINERARY_ITEM_FAILURE: 'REMOVE_ITINERARY_ITEM_FAILURE',
};

export default ItineraryActionsTypes;
